site_name: Brackets
site_description: React-ish, server-first SPA framework for Python
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Simple Mode: simple-mode.md
  - Quickstart: quickstart.md
  - Authoring:
      - Components (.bxc): bxc-authoring.md
      - Templates (.bx): templates.md
      - Routing: routing.md
      - Data & CRUD: data.md
      - Caching: cache.md
      - Security: security.md
  - Desktop: desktop.md
  - CLI: cli.md
  - Examples:
      - Counter: examples-counter.md
  - FAQ: faq.md
